project:
  type: website

website:
  title: ""
  navbar:
    left:
      - text: "About Me"
        href: about.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Blogs"
        href: blogs.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/samiulhaque/
      - icon: github
        href: https://github.com/samiulhq
execute:
  freeze: auto